/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.controller;


public enum OperationEnum {

    ADDCLIENT, GETALLCLIENTE, GETCLIENTEPERID, ADDESTRUTURA, ADDRESERVA, UPDATERESERVA,
    GETCLIENTEPERCPFORCNPJ, LOGINFUNCIONARIO, EHGERENTE, GETALLESTRUTURA, GETESTRUTURAPERID, ADDFUNCIONARIO, ADDGERENTE,
    GETALLFUNCIONARIO, GETALLGERENTE, GETFUNCIONARIOORGERENTEPERID, DISPONIBILIDADERESERVA, GETALLRESERVA, GETRESERVAPERID;


}
